### ISSUE TITLE
About the datasets

### ISSUE THREAD

**Issue by Sherlock-sen** [gamut-mapping/GamutNet#1]
I tried to download the datasets but couldn't connect to the servers. Would you please share a new link to download the datasets?

**Comment by hminle** [comment]
Oh, thank you so much to notice that. It seems that the server is down.
Let me re-up it, and come back with a new link

**Comment by Sherlock-sen** [comment]
And the paper can`t be download now. Would you please share the paper again?

**Comment by Sherlock-sen** [comment]
Thank you very much for your sharing and help.

**Comment by hminle** [comment]
Hi @Sherlock-sen ,
Please check out my website for the paper: https://hminle.com/
I am uploading the dataset, it is quite big, so may take me some time.
Will inform you the link as soon as it finishes

**Comment by hminle** [comment]
Hi @Sherlock-sen , I updated the dataset link:
Please check it out in the dataset section: https://github.com/gamut-mapping/GamutNet
