### ISSUE TITLE
About the inference

### ISSUE THREAD

**Issue by Sherlock-sen** [gamut-mapping/GamutNet#2]
I tried to test this wor but the experimental reasult are not satisfactory. Would you please share the test.py and ckpt files with me to realize verification and testing? Thanks from the bottom of my heart.

**Comment by hminle** [comment]
@Sherlock-sen Hi, thank for trying my work. I will prepare it and get back to you soon

**Comment by hminle** [comment]
Thank again for reminding me. Seems that I forgot to prepare the testing files carefully

**Comment by hminle** [comment]
Hi @Sherlock-sen : I added the pretrained model that I used to generate results in my paper.
https://github.com/gamut-mapping/GamutNet/tree/master/GamutNet_CIC2021_pretrained_model

I will add the test scripts too.
